[package]
name = "semiframes"
version = "0.1.0"
edition = "2021"

[dependencies]
nauty-Traces-sys = "0.9"
bitvec = "1.0"
clap = { version = "4.0", features = ["derive"] }
lalrpop-util = "0.20"
logos = "0.14"

[build-dependencies]
lalrpop = "0.20"